include: package:flutter_lints/flutter.yaml

# Cozmo library specific rules
linter:
  rules:
    # Allow print statements for debugging robot communication
    avoid_print: false
    # Allow constant names with underscores for protocol constants
    constant_identifier_names: false

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
